# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    tokens_creator.access_expiration_period: '%env(TOKEN_ACCESS_EXPIRATION_PERIOD)%'
    tokens_creator.refresh_expiration_period: '%env(TOKEN_REFRESH_EXPIRATION_PERIOD)%'
    app.recording_base_dir: '%env(resolve:ASTERISK_RECORDING_BASE_DIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Asterisk\RecordingService:
        arguments:
            $recordingBaseDir: '%app.recording_base_dir%'

    App\Service\Asterisk\Handler\:
        resource: '../src/Service/Asterisk/Handler/'
        autowire: true
        autoconfigure: true

    App\Service\Asterisk\Dispatcher\AsteriskEventDispatcher:
        arguments:
            $handlers: !tagged_iterator 'app.asterisk_event_handler'

    App\Service\Asterisk\Handler\DialBeginHandler:
        tags: ['app.asterisk_event_handler']

    App\Service\Asterisk\Handler\BridgeEnterHandler:
        tags: ['app.asterisk_event_handler']

    App\Service\Asterisk\Handler\HangupHandler:
        tags: ['app.asterisk_event_handler']

    App\Service\Asterisk\Handler\SoftHangupRequestHandler:
        tags: [ 'app.asterisk_event_handler' ]

    App\Service\Asterisk\Handler\ContactStatusHandler:
        tags: [ 'app.asterisk_event_handler' ]

    App\Service\Asterisk\Handler\DeviceStateChangeHandler:
        tags: [ 'app.asterisk_event_handler' ]
