[general]
static=yes
writeprotect=no

[internal]

; 1001 -> 1002 va boshqa 10XX ichki qo'ng'iroqlar
exten => _10XX,1,NoOp(Internal call from ${CALLERID(num)} to ${EXTEN})
 same => n,Set(__CALLER=${FILTER(0-9,${CALLERID(num)})})
 same => n,Set(__CALLEE=${FILTER(0-9,${EXTEN})})
 same => n,Set(__LINKEDID=${CHANNEL(linkedid)})
 same => n,Set(__REC_FILE=${LINKEDID}.wav)
 same => n,NoOp(Recording file: ${REC_FILE})
 same => n,Dial(PJSIP/${EXTEN},30,b(record^s^1(${REC_FILE})))
 same => n,Hangup()



; Test uchun echo recording
exten => 1003,1,NoOp(Test echo with recording)
 same => n,Answer()
 same => n,Set(__LINKEDID=${CHANNEL(linkedid)})
 same => n,Set(__REC_FILE=${LINKEDID}-test.wav)
 same => n,MixMonitor(${REC_FILE})
 same => n,Echo()
 same => n,StopMixMonitor()
 same => n,Hangup()

; Test uchun ovozli xabar
exten => 888,1,Playback(hello-world)
 same => n,Hangup()

[record]
exten => s,1,NoOp(Start recording file ${ARG1})
 same => n,MixMonitor(${ARG1},b)
 same => n,Return()
