[general]
static = yes
writeprotect = no

[internal]
; 1001 dan 1002 ga qo'ng'iroq
exten => 1002,1,Dial(PJSIP/1002,30)
exten => 1002,n,Hangup()

; 1002 dan 1001 ga qo'ng'iroq
exten => 1001,1,Dial(PJSIP/1001,30)
exten => 1001,n,Hangup()

; Test uchun (ovozli xabar)
exten => 888,1,Playback(hello-world)
exten => 888,n,Hangup()

[internal]

exten => _10XX,1,NoOp(Call started)
 same => n,Set(FILENAME=${UNIQUEID})
 same => n,MixMonitor(${FILENAME}.wav)
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()
