[modules]
autoload = 1

; PJSIP uchun kerakli modullar
load => res_sorcery_config.so
load => res_sorcery_memory.so
load => res_pjproject.so
load => chan_pjsip.so
load => res_manager.so

; Dialplan uchun
load => pbx_config.so

; Logging uchun
load => logger.so
