; ==================== TRANSPORT ====================
[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060
external_media_address = 192.168.172.236   ; Kali IP manzilingiz
external_signaling_address = 192.168.172.236
local_net = 192.168.0.0/16
; ==================== ENDPOINT 1001 ====================
[1001]
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
auth = 1001-auth
aors = 1001
direct_media = no

[1001-auth]
type = auth
auth_type = userpass
password = 1234
username = 1001

[1001]
type = aor
max_contacts = 5
qualify_frequency = 30

; ==================== ENDPOINT 1002 ====================
[1002]
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
auth = 1002-auth
aors = 1002
direct_media = no

[1002-auth]
type = auth
auth_type = userpass
password = 1234
username = 1002

[1002]
type = aor
max_contacts = 5
qualify_frequency = 30
