; ==================== TRANSPORT ====================
[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060
external_media_address = 192.168.172.236   ; Kali IP manzilingiz
external_signaling_address = 192.168.172.236
local_net = 192.168.0.0/16
#include pjsip_extensions.conf
